### ISSUE TITLE
Missing modprobe, $PATH confusion

### ISSUE THREAD

**Issue by attah** [CODeRUS/sfos-builder#3]
I was trying to build an image for tbj, and ended up having to do some tweaks for it to work as expected:

```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,6 +11,9 @@ RUN set -ex ;\
   chmod +x /usr/local/bin/* ;\
   test -f /usr/bin/atruncate || zypper -n in atruncate ;\
   test -f /usr/sbin/lvcreate || zypper -n in lvm2 ;\
-  test -f /usr/bin/pigz || zypper -n in pigz
+  test -f /usr/bin/pigz || zypper -n in pigz ;\
+  test -f /usr/sbin/modprobe || zypper -n in kmod ;\
+  test -f /bin/grep || ln -s /usr/bin/grep /bin/grep ;\
+  test -f /usr/bin/img2simg_jolla || ln -s /usr/local/bin/img2simg_jolla /usr/bin/img2simg_jolla

ENTRYPOINT ["/usr/local/bin/build.sh"]
```

This is of course not the correct solution, but provided as reference. 

When grep and img2simg_jolla are missing, the build fails semi-silently.

It could also be worth noting that the required credentials needs to come from the exact same device, so this will be hard to do after a device has been bricked.

**Comment by CODeRUS** [comment]
fixed in 6c840615d13b142227e5bd6e778c5a87ee6fb405

as for credentials: i'm using creds from jolla c, seems to work for all devices i have.

**Comment by attah** [comment]
Thanks!
Sadly my Jolla C credentials doesn't even work for l500d. I deliberately left it at 3.4 to have something to test with since my J1 is dead. So i tried matching the version... still unauthorized. Could be you have special privileges...
Edit: oh. well... tablet credentials works :)

**Comment by CODeRUS** [comment]
well thats the jolla restrictions for given repositories we cant avoid.
other solution could be to mirror these repositories, but there are a lot of terabytes of space required :D
anyway i think if someone need image but cant get creds, other people can build it and share
